version: '2.4'

services:
  postgres:
    image: postgres:15-alpine
    container_name: templog-postgres
    environment:
      POSTGRES_DB: templog
      POSTGRES_USER: temploguser
      POSTGRES_PASSWORD: templogpass
    ports:
      - "5432:5432"  # проброс порта для доступа к БД с хоста (опционально)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: templog-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/templog
      SPRING_DATASOURCE_USERNAME: temploguser
      SPRING_DATASOURCE_PASSWORD: templogpass
      WEATHER_API_KEY: ${WEATHER_API_KEY}  # ключ будет подставлен из .env или окружения
      WEATHER_API_URL: ${WEATHER_API_URL}
    ports:
      - "8080:8088"

volumes:
  postgres_data: